# Generated by Django 5.1 on 2024-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_category_product_color_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
